### ISSUE TITLE
Compatible with 2018.2 Addressables system 

### ISSUE THREAD

**Issue by yosun** [SadPandaStudios/AssetBundleManager#10]
Looking at a proper AssetBundles framework, but noticed that it seems that Unity is re-architecting this into some sort of Addressables system in 2018.2 

Are you planning to make this compatible with the current stable Unity version? https://forum.unity.com/threads/assetbundle-manager-deprecated.528334/

**Comment by FodderMK** [comment]
Once Unity 2018.2 is out of beta and they've added some documentation to the Addressables system I'll take a look and see if anything needs to be done.

**Comment by FodderMK** [comment]
Where I stand right now, I think the addressables system would be a replacement for ABM.  I don't believe there would be much value adding support, it would probably be more of a rewrite?  Going to close this for now but will continue to keep it in mind.
