### ISSUE TITLE
Uploading asset bundles on server

### ISSUE THREAD

**Issue by guizmo01** [SadPandaStudios/AssetBundleManager#15]
Hi, I have a question:

When uploading the asset bundle on server does it need to have all files that were generated or having just the .unity3d is enough?

I am planning of downloading the asset bundles into persistent path and load them from there, does that mean I have to tweak anything in  your code?

**Comment by FodderMK** [comment]
You need to have all the files that were generated when building the asset bundles.

As for the persistent path, Unity typically manages the bundles itself.  By this I mean Unity already has a caching system so you shouldn't have to manually manage a cache using the persistent path.  If that's something you want to do then you will need to write code.
