### ISSUE TITLE
Every script need to write a AssetBundle manager ?

### ISSUE THREAD

**Issue by JoneRen** [SadPandaStudios/AssetBundleManager#17]
When download bundle from different script , does very script have to has it own abm, and initialize ,then download bundle from server or cache, can you provide an ABM singleton can initialize once and directly load bundle ?

**Comment by FodderMK** [comment]
ABM can be reused across multiple scripts.  Create an instance, initialize it, then reuse that instance wherever you need it.  The only requirement is waiting for it to be initialized before you call `GetBundle`. 
 You can put it in a singleton if you want.

```csharp
public static class Singletons
{
  public static AssetBundleManager Abm;
}
```

```csharp
public class InitializationController : MonoBehaviour
{
  private void Start()
  {
    Singletons.Abm = new AssetBundleManager();
    // Finish initializing ABM here
    [...]
  }
}
```
```csharp
public class GameController : MonoBehaviour
{
  private void Start()
  {
    Singletons.Abm.GetBundle("MyBundle", OnBundleDownloaded);
  }
  [...]
}
```

**Comment by JoneRen** [comment]
yes， already did this,  moreover, abm single have to provide the unload interface, when ever call the singleton load the bundle, have to call abm singleton unload(). thinking of how to simplfy this by using juse one call.

**Comment by JoneRen** [comment]
```
public class ABMSingleton{

	public AssetBundleAsync GetBundleAsync(string bundleName){		

		return abm.GetBundleAsync(bundleName);				
	}

	public void GetBundle(string bundleName, Action<AssetBundle> onComplete){
		abm.GetBundle(bundleName, onComplete);
	}
	
	public void UnloadBundle(AssetBundle bundle){
		abm.UnloadBundle(bundle);
	}
}
```

what I mean is user have to call 2 functions 
1. GetBundle()
2. UnloadBundle().
