### ISSUE TITLE
how to config ABM for this situation?

### ISSUE THREAD

**Issue by JoneRen** [SadPandaStudios/AssetBundleManager#18]
Hi, 
I wanna first thank you for this project, it's indeed easier to use than Unity's abm, and I use it in my project.  I had some question about how to config the ABM for this scenario.
our project use asset bundle browser to build asset bundles.
Q: 
1. After build the asset bundles, we put all abs in to a asset server and put some of the abs into streaming asset folder which can be load and played offline,
how can I configure the ABM to enable it can check the asset bundle cache version, if it's cache, it just load from streamingasset folder, if the cache version is old , it will download from server. 

I try this code 
`abm = new AssetBundleManager();		
		abm.SetPrioritizationStrategy(AssetBundleManager.PrioritizationStrategy.PrioritizeStreamingAssets);
        abm.SetBaseUri(GameConfig.GetBaseURI());`

I'm not sure it's going to work, 

2. Asset bundle browser build generate the manifest for every asset, in our project, most asset has no dependency, It there any interface that can skip check the manifest dependency globally or for a specific asset bundle ?

3.If I put the IOS, and IOS meanfest bundle in streammingAsset folder,  when game start up, It should always to load the IOS ab from asset server, How can I make sure it work in this way when the network is connectable.?

4. when I use abm.UseStreamingAssetsFolder(), and the IOS path is correct, it always show host is not connectable ?   how can i fix this ?

sorry for ask so many questions in a time.

thanks

**Comment by FodderMK** [comment]
1. The behavior you're looking for is the default behavior.  ABM will use the remote bundles if they are different from the streaming bundles.  When ABM downloads the remote bundles it caches them for use later (with the exception of the manifest bundle which is always downloaded)  You don't need to change the prioritization strategy.  `PrioritizeStreamingAssets` tells ABM to always use StreamingAssets if they exist.

2. When you try to download a bundle ABM will check the primary manifest to see if there are any dependencies and download those as well.  If the bundle has no dependencies then nothing extra will be downloaded.  This operation is all done locally and should have minimal to no impact on performance.  Why don't you want it to check for dependencies?

3. This should be the default behavior.  Are you seeing something different?

4. When you call `UseStreamingAssetsFolder` then ABM will only use that folder, it will not try to connect to a remote server.  Can you provide some code and a log of what you're seeing?

**Comment by JoneRen** [comment]
Hi Fodder,
thanks for your explanation.
Currently I build all the asset bundles by ABB, and copy all file to streammingAsset folder, including the platform file (iOS, iOS.manifest...), 
abm = new AssetBundleManager(); 
abm.SetBaseUri(GameConfig.GetBaseURI());
use this code to initialize abm.

when I install the builds and run on devices. 
what is want is all the download files should be cached (except iOS.manifest), and should load from streamingAsset folder to fast loading asset.
but the log says all files are uncached , and load from remote server.

**Comment by JoneRen** [comment]
and also when disconnect the network, the abm still try to downloading from remote server, didn't try to load from StreammingAsset folder.

"
The behavior you're looking for is the default behavior. ABM will use the remote bundles if they are different from the streaming bundles. When ABM downloads the remote bundles it caches them for use later (with the exception of the manifest bundle which is always downloaded) You don't need to change the prioritization strategy. PrioritizeStreamingAssets tells ABM to always use StreamingAssets if they exist.
"

how abm check the difference between the remote server and streammingasset folder ?

**Comment by FodderMK** [comment]
> but the log says all files are uncached , and load from remote server.

I'll test this scenario out this weekend.  It might be helpful if you include the full log as well.

> how abm check the difference between the remote server and streammingasset folder ?

Asset bundle manifest files contain hashes for every bundle.  When you tell ABM to get a bundle it compares the hash for that bundle in the remote location against the one in the StreamingAssets folder.  If the hash is the same it uses the bundle in StreamingAssets, otherwise it download the bundle from the remote location.

**Comment by JoneRen** [comment]
Hi Fodder,
I've found the issue, it's the problem when build iOS project, the streamingasset folder doesn't copy to device correctly, so every time abm has to load from server.
you don't need to test that.  
except that, I found this method in ABM.cs

`
        private void GenerateUnhashToHashMap(AssetBundleManifest manifest)
        {
            unhashedToHashedBundleNameMap.Clear();

            var splitChar = new[] { '_' };
            var allBundles = manifest.GetAllAssetBundles();

            for (int i = 0; i < allBundles.Length; i++) {
                var split = allBundles[i].Split(splitChar, 2);
                if (split.Length != 2) continue;
                unhashedToHashedBundleNameMap[split[0]] = allBundles[i];
            }
        }`

I'm not totally understand what's this function do and why the bundle name has to be "x_x", I found my bundle name is not that but still works fine.
do we have the name rules for bundle name ?

**Comment by FodderMK** [comment]
AssetBundleBrowser has the option `Append Hash`, which will add the bundle hash to the bundle file name. 
 When they are built like this the end result is a file with a name like `FILENAME_HASH`.  The function above is to split out the hash from the filename.  You shouldn't need to worry about this if you are not making bundles with `Append Hash` checked.
