### ISSUE TITLE
StandaloneWindows bundle name

### ISSUE THREAD

**Issue by RDeluxe** [SadPandaStudios/AssetBundleManager#22]
Hi,

We are still using this asset, thanks again!

We are building and uploading our ABs using Unity Cloud (in the Post Process step). 
It seems that if we build the ABs with "Windows 64" as the build target the output folder is named `StandaloneWindows64`, same for the manifest.

``` csharp
private static void BuildAssetBundles() {
  var buildPath = GetAssetBundleFolder();

  if (Directory.Exists(buildPath)) {
    Directory.Delete(buildPath, true);
  }

  Directory.CreateDirectory(buildPath);

  // Build asset bundles for the current platform
  BuildPipeline.BuildAssetBundles(buildPath, BuildAssetBundleOptions.None, EditorUserBuildSettings.activeBuildTarget);
}

private static string GetAssetBundleFolder() {
  return "Assets/StreamingAssets" + "/" + EditorUserBuildSettings.activeBuildTarget;
}
```

But ofc in `AssetBundleUtility.GetPlatformForAssetBundles` the bundle name is always set to `StandaloneWindows` and not `StandaloneWindows64`.

Not quite sure what to make of that, the best solution would probably be to rename the output folder and manifest during Cloud Build for the windows 64bit target.

Or we could check if windows is 64bits at runtime using [this method](https://docs.unity3d.com/ScriptReference/SystemInfo-operatingSystem.html) and select the appropriate bundle name.

**Comment by FodderMK** [comment]
My understanding is that `StandaloneWindows` and `StandaloneWindows64` are actually the same types when it comes to asset bundles, which is why `AssetBundleUtility.GetPlatformForAssetBundles` is written the way it is.  What might be easiest is to change your `BuildAssetBundles` script to build bundles for `StandaloneWindows` when the active build target is `StandaloneWindows64`. Alternatively you could modify `AssetBundleUtility.GetPlatformForAssetBundles` to return `StandaloneWindows64` when the build target is `StandaloneWindows64`.

**Comment by RDeluxe** [comment]
Thank you, I created a small helper that I use while building the ABs to get the platform name

```csharp
        private static BuildTarget GetAssetBundleBuildTarget(BuildTarget target) {
            switch (target) {
                case BuildTarget.StandaloneWindows64:
                    return BuildTarget.StandaloneWindows;
                case BuildTarget.StandaloneLinux64:
                    return BuildTarget.StandaloneLinux;
                default:
                    return target;
            }
        }
```

```csharp
            BuildPipeline.BuildAssetBundles(buildPath, BuildAssetBundleOptions.None, GetAssetBundleBuildTarget(EditorUserBuildSettings.activeBuildTarget));
```

We can close this issue !
