### ISSUE TITLE
Support Unity Fast Play Mode (without assembly reloading)

### ISSUE THREAD

**Issue by RDeluxe** [SadPandaStudios/AssetBundleManager#23]
https://docs.unity3d.com/Manual/DomainReloading.html

This can be done by adding

```cshparp
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void ResetOnPlay() {
            instance = null;
        }
```

to AssetBundleDownloaderMonoBehaviour

That should be enough !

**Comment by FodderMK** [comment]
`AssetBundleDownloaderMonoBehaviour` tries to kill the static on it's `OnDestroy` method:

```csharp
private void OnDestroy()
{
    if (instance == this) {
        instance = null;
    }
}
```

Does that not work with DomainReloading disabled?
