### ISSUE TITLE
Using StreamingAssets Folder Fails

### ISSUE THREAD

**Issue by YY1377** [SadPandaStudios/AssetBundleManager#24]
Hi,
I am trying to use asset bundles from StreamingAssets folder on Android. 
<img width="453" alt="Screen Shot 2020-07-27 at 16 48 16" src="https://user-images.githubusercontent.com/9296189/88549443-f96a8b80-d028-11ea-97ce-54a8c1b8ffa4.png">
<img width="445" alt="Screen Shot 2020-07-27 at 16 47 59" src="https://user-images.githubusercontent.com/9296189/88549538-1606c380-d029-11ea-9a66-12d12f426317.png">

You can see above how I built and the resulting files.

When I start the app and investigate logcat, it says :
Error Unity Unable to open archive file: jar:file:///data/app/com.a.b-1/base.apk!/assets/Android/Android 

Warn Unity Unable to retrieve manifest file [jar:file:///data/app/com.a.b-1/base.apk!/assets/Android/Android] from StreamingAssets, disabling StreamingAssetsBundleDownloadDecorator. 
...

And also I see that when I extract the apk:
<img width="482" alt="Screen Shot 2020-07-27 at 17 14 08" src="https://user-images.githubusercontent.com/9296189/88552380-b3172b80-d02c-11ea-8659-3b438ef125b3.png">

Is there a problem with my file hierarchy?

PS: Thanks for the awesome library!

**Comment by FodderMK** [comment]
You were able to figure it out?

**Comment by YY1377** [comment]
Yeah, my fault. Thank you

**Comment by sam1am** [comment]
Having the same problem. Would love the solution.

**Comment by DK013** [comment]
> Hi, I am trying to use asset bundles from StreamingAssets folder on Android. <img alt="Screen Shot 2020-07-27 at 16 48 16" width="453" src="https://user-images.githubusercontent.com/9296189/88549443-f96a8b80-d028-11ea-97ce-54a8c1b8ffa4.png"> <img alt="Screen Shot 2020-07-27 at 16 47 59" width="445" src="https://user-images.githubusercontent.com/9296189/88549538-1606c380-d029-11ea-9a66-12d12f426317.png">
> 
> You can see above how I built and the resulting files.
> 
> When I start the app and investigate logcat, it says : Error Unity Unable to open archive file: jar:file:///data/app/com.a.b-1/base.apk!/assets/Android/Android
> 
> Warn Unity Unable to retrieve manifest file [jar:file:///data/app/com.a.b-1/base.apk!/assets/Android/Android] from StreamingAssets, disabling StreamingAssetsBundleDownloadDecorator. ...
> 
> And also I see that when I extract the apk: <img alt="Screen Shot 2020-07-27 at 17 14 08" width="482" src="https://user-images.githubusercontent.com/9296189/88552380-b3172b80-d02c-11ea-8659-3b438ef125b3.png">
> 
> Is there a problem with my file hierarchy?
> 
> PS: Thanks for the awesome library!

Hi I'm having the same problem. It'll really help and save my time if you can provide the solution you came accross. Thanks

**Comment by onculfm** [comment]
> > Hi, I am trying to use asset bundles from StreamingAssets folder on Android. <img alt="Screen Shot 2020-07-27 at 16 48 16" width="453" src="https://user-images.githubusercontent.com/9296189/88549443-f96a8b80-d028-11ea-97ce-54a8c1b8ffa4.png"> <img alt="Screen Shot 2020-07-27 at 16 47 59" width="445" src="https://user-images.githubusercontent.com/9296189/88549538-1606c380-d029-11ea-9a66-12d12f426317.png">
> > You can see above how I built and the resulting files.
> > When I start the app and investigate logcat, it says : Error Unity Unable to open archive file: jar:file:///data/app/com.a.b-1/base.apk!/assets/Android/Android
> > Warn Unity Unable to retrieve manifest file [jar:file:///data/app/com.a.b-1/base.apk!/assets/Android/Android] from StreamingAssets, disabling StreamingAssetsBundleDownloadDecorator. ...
> > And also I see that when I extract the apk: <img alt="Screen Shot 2020-07-27 at 17 14 08" width="482" src="https://user-images.githubusercontent.com/9296189/88552380-b3172b80-d02c-11ea-8659-3b438ef125b3.png">
> > Is there a problem with my file hierarchy?
> > PS: Thanks for the awesome library!
> 
> Hi I'm having the same problem. It'll really help and save my time if you can provide the solution you came accross. Thanks

Use Better Streaming Assets
