### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by JackM36** [SadPandaStudios/AssetBundleManager#8]
I am looking to get the download progress so I can show a progress bar (More than one bundle may be downloaded) to the user. Any tips where should I dig into to achieve this?

**Comment by FodderMK** [comment]
Take a look at the `feature/download-progress-hook` branch.  I'm not big on this implementation but am curious if it meets your needs and whether it's worth pursuing further.  This won't work with the manifest (which is typically very fast anyway) or streaming assets.

To use it:
```
abm.GetBundle("mybundle", OnAssetBundleDownloaded);
abm.RegisterDownloadProgressHandler("mybundle", f => Debug.Log(f));
```
`f` will be a value between 0 and 1 unless there is an error in which case it should be -1.

**Comment by JackM36** [comment]
Thanks, I will give it a try.
Eventually what I need is to display the user with a download progress bar while waiting for bundles (multiple) to download.

I guess I can register to multiple downloadProgressHandlers and then average them to display the resulting download progress right? (The user does not need to know whether there is one or multiple bundles downloading.)

**Comment by FodderMK** [comment]
Yes, you could subscribe multiple times, once for each bundle.  This implementation is rough but shows what is possible.

**Comment by JackM36** [comment]
I tried it, and implemented a structure to allow me to average the download progress of multiple bundles. So far it works great, thanks!

I will let you know if something comes up.

**Comment by FodderMK** [comment]
Glad to hear it!
