### ISSUE TITLE
Cached bundle

### ISSUE THREAD

**Issue by brickhawkins** [SadPandaStudios/AssetBundleManager#9]
Hi, thank you for sharing your ABM
but there's a lot question i want to ask.

How to check if the bundle is already in cache? 
and i'm a bit confused about how you compare the version? your code is using caching.IsVersionCached but how i get the Hash128 form AssetBundleDownloadCommand?

I want to make a list of downloadable content (with notification if the downloaded version is updated)

**Comment by FodderMK** [comment]
One of the main purposes for making ABM is to have the caching system transparent to the programmer so there hadn't been a reason to create an IsVersionCached call before.  I have added one now.  Once abm has been initialized you can check if a version is cached with the following:

```
if (abm.IsVersionCached("MyAssetBundle"))
  Debug.Log("Bundle is cached");
else
  Debug.Log("Bundle needs to be downloaded");
```
This does not take into account StreamingAssets.

For future reference you can get the hash for a bundle via `abm.Manifest`

**Comment by brickhawkins** [comment]
I'm Sorry just back from long vacation, Thanks a lot
I'm trying it right now.
